name: routes_flutter_web
description: Routes Flutter Web
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: null
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: ^4.3.8
  url_strategy: ^0.2.0

dev_dependencies:
  auto_route_generator: null
  build_runner: null
  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
